# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d82adf982d3b29473270422a72e8259e408ede6ce6b18ead2deb81be16bdc05e531cd9641c43d94b7a79e20263b2f84f28a9afe29c3e17684be4793dce0773bf

test:
  secret_key_base: ee9b8a2e572b76e3e8f9bae87e24d68ca7725c25afdffa5034835e1b5c3094eeba9d61fb707d33e876222ea8789c015197396b34179031bced54fcf0e514cbef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
